[build]
  command = "NODE_ENV=production npm install && NODE_ENV=production npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/auth/*"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/api/admin/*"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/api/analyze"
  to = "/.netlify/functions/analyze"
  status = 200
