export const sampleRecipes = [
  { id: 1, name: 'Avocado Toast with Poached Eggs', category: 'breakfast', time: 15, difficulty: 'easy', vegan: false, vegetarian: true, lowCarb: false, keto: false, glutenFree: true, highProtein: false, noCook: false, ingredients: ['bread', 'avocado', 'eggs', 'lemon', 'salt', 'pepper', 'red pepper flakes'], instructions: 'Toast bread. Mash avocado with lemon juice, salt, and pepper. Poach eggs. Top toast with avocado and poached eggs. Sprinkle red pepper flakes.', prepTime: 5, cookTime: 10, calories: 320, protein: 14 },
  { id: 2, name: 'Mediterranean Chickpea Bowl', category: 'lunch', time: 20, difficulty: 'easy', vegan: true, vegetarian: true, lowCarb: false, keto: false, glutenFree: true, highProtein: true, noCook: true, ingredients: ['chickpeas', 'cucumber', 'tomato', 'red onion', 'feta', 'olive oil', 'lemon', 'oregano'], instructions: 'Drain chickpeas. Chop cucumber, tomato, red onion. Combine all in bowl. Crumble feta on top. Dress with olive oil, lemon juice, and oregano.', prepTime: 15, cookTime: 5, calories: 380, protein: 15 },
  { id: 3, name: 'Grilled Chicken Stir-Fry', category: 'dinner', time: 25, difficulty: 'medium', vegan: false, vegetarian: false, lowCarb: true, keto: true, glutenFree: true, highProtein: true, noCook: false, ingredients: ['chicken breast', 'broccoli', 'bell peppers', 'soy sauce', 'garlic', 'ginger', 'sesame oil', 'rice'], instructions: 'Slice chicken and marinate in soy sauce, garlic, ginger. Stir-fry chicken until cooked. Add vegetables and cook until tender. Serve over rice.', prepTime: 10, cookTime: 15, calories: 420, protein: 38 },
  { id: 4, name: 'Berry Smoothie Bowl', category: 'breakfast', time: 10, difficulty: 'easy', vegan: true, vegetarian: true, lowCarb: false, keto: false, glutenFree: true, highProtein: false, noCook: true, ingredients: ['mixed berries', 'banana', 'spinach', 'almond milk', 'chia seeds', 'granola', 'coconut flakes'], instructions: 'Blend berries, banana, spinach, almond milk until thick. Pour into bowl. Top with granola, chia seeds, and coconut flakes.', prepTime: 5, cookTime: 5, calories: 280, protein: 6 },
  { id: 5, name: 'Salmon and Asparagus Foil Pack', category: 'dinner', time: 30, difficulty: 'easy', vegan: false, vegetarian: false, lowCarb: true, keto: true, glutenFree: true, highProtein: true, noCook: false, ingredients: ['salmon fillet', 'asparagus', 'lemon', 'dill', 'olive oil', 'garlic', 'salt'], instructions: 'Place salmon and asparagus on foil. Drizzle with olive oil, lemon juice, garlic, dill. Seal foil. Bake at 400°F for 20 min.', prepTime: 10, cookTime: 20, calories: 350, protein: 32 },
  { id: 6, name: 'Zucchini Noodle Pesto', category: 'dinner', time: 15, difficulty: 'easy', vegan: true, vegetarian: true, lowCarb: true, keto: true, glutenFree: true, highProtein: false, noCook: false, ingredients: ['zucchini', 'basil pesto', 'cherry tomatoes', 'pine nuts', 'parmesan', 'garlic', 'olive oil'], instructions: 'Spiralize zucchini. Sauté briefly. Toss with pesto, cherry tomatoes, pine nuts. Top with parmesan shavings.', prepTime: 10, cookTime: 5, calories: 310, protein: 8 },
  { id: 7, name: 'Overnight Oats', category: 'breakfast', time: 10, difficulty: 'easy', vegan: false, vegetarian: true, lowCarb: false, keto: false, glutenFree: false, highProtein: true, noCook: true, ingredients: ['oats', 'milk', 'yogurt', 'honey', 'berries', 'nuts'], instructions: 'Mix oats, milk, yogurt, honey in jar. Refrigerate overnight. Top with berries and nuts in the morning.', prepTime: 5, cookTime: 0, calories: 350, protein: 12 },
  { id: 8, name: 'Caprese Salad', category: 'lunch', time: 10, difficulty: 'easy', vegan: false, vegetarian: true, lowCarb: true, keto: true, glutenFree: true, highProtein: false, noCook: true, ingredients: ['mozzarella', 'tomatoes', 'basil', 'olive oil', 'balsamic glaze', 'salt'], instructions: 'Slice mozzarella and tomatoes. Layer with basil. Drizzle olive oil and balsamic glaze. Season with salt.', prepTime: 10, cookTime: 0, calories: 280, protein: 16 },
  { id: 9, name: 'Black Bean Tacos', category: 'dinner', time: 20, difficulty: 'easy', vegan: true, vegetarian: true, lowCarb: false, keto: false, glutenFree: false, highProtein: true, noCook: false, ingredients: ['black beans', 'tortillas', 'avocado', 'lime', 'cilantro', 'onion', 'cumin', 'chili powder'], instructions: 'Season and heat black beans with cumin and chili powder. Warm tortillas. Assemble with beans, avocado, cilantro, onion, and lime.', prepTime: 10, cookTime: 10, calories: 340, protein: 14 },
  { id: 10, name: 'Tuna Nicoise', category: 'lunch', time: 25, difficulty: 'medium', vegan: false, vegetarian: false, lowCarb: true, keto: false, glutenFree: true, highProtein: true, noCook: false, ingredients: ['tuna', 'eggs', 'green beans', 'potatoes', 'olives', 'tomatoes', 'anchovy', 'olive oil'], instructions: 'Boil eggs and potatoes. Blanch green beans. Arrange all ingredients. Dress with olive oil and anchovy.', prepTime: 10, cookTime: 15, calories: 390, protein: 28 },
]

export const detectedIngredientMap = {
  'tomato': ['tomatoes', 'tomato'],
  'onion': ['onion', 'red onion', 'white onion'],
  'chicken': ['chicken', 'chicken breast', 'chicken thigh'],
  'egg': ['eggs', 'egg'],
  'bread': ['bread', 'sourdough', 'toast'],
  'rice': ['rice', 'white rice', 'brown rice'],
  'broccoli': ['broccoli'],
  'spinach': ['spinach', 'leafy greens'],
  'avocado': ['avocado'],
  'cheese': ['cheese', 'mozzarella', 'feta', 'parmesan'],
  'milk': ['milk', 'almond milk', 'oat milk'],
  'salmon': ['salmon', 'fish'],
  'potato': ['potato', 'potatoes'],
  'pasta': ['pasta', 'noodles', 'zucchini noodle'],
  'bean': ['beans', 'black beans', 'chickpeas', 'lentils'],
  'carrot': ['carrot', 'carrots'],
  'pepper': ['pepper', 'bell pepper'],
  'corn': ['corn'],
  'mushroom': ['mushroom', 'mushrooms'],
  'lemon': ['lemon'],
  'garlic': ['garlic'],
}
